apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-cm
data:
  ENABLE_JSON_LOGGING: "true"
  LOG_LEVEL: "INFO"
  LOG_LEVEL_SI: "DEBUG"
  LOGBACK_FILE: "logback-json.xml"
  JAVA_OPTS: "-XX:+UseSerialGC -XX:MaxRAMPercentage=50 -XX:InitialRAMPercentage=25 -XX:+UseStringDeduplication -Ddebug"
  POSTGRES_SHOW_SQL: "false"
  POSTGRES_SSL_MODE: "prefer"