apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  selector:
    app: service
  ports:
    - name: http-api
      port: 8080
      targetPort: 8080
      appProtocol: http
---
apiVersion: v1
kind: Service
metadata:
  name: metrics
  labels:
    app: metrics
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: /metrics/prometheus
    prometheus.io/port: '8081'
    signal-iduna.de/prometheus.scrape: "true"
    signal-iduna.de/prometheus.port: "8081"
    signal-iduna.de/prometheus.path: "/metrics/prometheus"  
spec:
  selector:
    app: metrics
  ports:
    - name: http-metrics
      port: 8081
      protocol: TCP
      targetPort: 8081
