apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: <service-name>
spec:
  selector:
    matchLabels:
      app: <service-name>
  template:
    metadata:
      labels:
        app: <service-name>
    spec:
      containers:
        # Resources quotas soll anhand der anforderung von dem Service angepasst werden.
        - name: app
          resources:
            limits:
              cpu: 400m
              memory: 950Mi
            requests:
              cpu: 200m
              memory: 500Mi