apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: "-hint"

resources:
  - ../../base

components:
  - ../../base/components/postgres
  - ../components/postgres
  - ../../base/components/mongo
  - ../components/mongo

labels:
  - pairs:
      app: hint
      service: hint-service

images:
  - name: app-image
    newName: dev.docker.system.local/elpa-hint-tst/hint
    newTag: 33909f4.1440

configMapGenerator:
  - name: backend-cm
    behavior: merge
    literals:
      - SERVICE_NAME=hint
      - POSTGRES_SCHEMA_NAME=hin_develop
      - AUTH_URL=https://employee.login.int.signal-iduna.org/

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: app
  - path: service-app-patch.yaml
    target: 
      kind: Service
      name: app
  - patch: virtualservice-patch.yaml
    target: 
      kind: VirtualService
      name: virtualservice

      


