apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - path: deployment-patch.yaml
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: KAFKA_CLIENT_ID
          value: "$(SERVICE_NAME)-$(K8S_POD_NAME)"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: KAFKA_CONSUMER_GROUP
          value: "$(SERVICE_NAME)-$(K8S_ENVIRONMENT_LABEL)"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: KAFKA_TOPIC_SUFFIX
          value: "-$(K8S_ENVIRONMENT_LABEL)"
    target:
      group: apps
      version: v1
      kind: Deployment
      name: app