# Default values for percona-mongodb-si.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3
prefix: db1
deletePvcOnDelete: false


# Versionskompatibilitaet beachten https://docs.percona.com/percona-operator-for-mongodb/versions.html
image:
  name: percona/percona-server-mongodb:6.0.19-16
  backup: percona/percona-backup-mongodb:2.8.0
  crVersion: 1.19.1

label: mongodb
labelName: database

secret:
  name: my-cluster-name-secrets

pause: false
enableVolumeExpansion: true

unsafeFlags:
  replsetSize: false

resources:
  limits:
    cpu: "2000m"
    memory: "2000Mi"
  requests:
    cpu: "100m"
    memory: "500Mi"
  storage: 10

backup:
  enabled: false