apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ .Values.prefix }}-authpolicy-allow-internal-mongodb
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: percona-server-mongodb # WÃ¤hle die MongoDB Pods aus
  action: ALLOW 
  rules:
  - from:
    - source:
        namespaces: ["{{ required "A valid .Values.namespace entry required!" .Values.namespace }}"]
