apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.prefix }}-networkpolicy-allow-mongodb
spec:
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: percona-server-mongodb
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: percona-server-mongodb
  podSelector:
    matchLabels:
      app.kubernetes.io/name: percona-server-mongodb
  policyTypes:
    - Ingress
    - Egress