---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: {{ .Values.prefix }}-olly-secret
  namespace: '{{ .Values.namespace }}'
spec:
  encryptedData:
    {{- if eq .Values.stage "prd" }}
    PASSWORD: AgBSF44jVWxsKbEfw0U3ukF2xmpYU11T6fZgkG1KNfGT29YTyuk0RxTwEE9DN1pZmh51Ys8nN4fJIDoCU8MGsyq/bdp4OV5VEG2smGyCmaTP0bNn55AFqn1Kv2Yop6ECJ8pn964lfPnoE8pYgkCfxrcWd3MsX+vUm+Oro7JJYlqaEbkef6a+hpzpOdG/lpprIKaWHU4wzdKlYQg+bXNJVkktq337JOumAB1YYq+ADYoqip50qYrg7szP1yZ+tGUuTn3oDQ921QIx3qh7Vz67IHIbAEx12/X57LWnoPIsOMjsQY1W1r5BCLwD7TL9rBsLga4cI8yv6EzMtAbAl7Ns0O0b63SN82nQN0eJqLzNCefv/ghjxX9MP8d5LizYKOMEvyTD06QLAeWm1fZz5oyN1le/ETe15u0TYbyEcOJP2y/OEM8CWqJLkNMhlour+Bewb7nNTYgCVf4pVvgtXVzmtYXp/QIZfZbMuQrqPzidMWQJr5bR+Yfrs5Thw/C64kJmzfdRM5UeaxuTZT/iS2qM7ZyqT5xD30Gxegbi7q0Vu8Vz+qoAyQKk1NxWgNK8MFame/whP6h7Pjuku66Dpf10HwU2y7fqWZXDLyuEdOjsDmRXy8ZCRJJdEQKWT6E7n36wwP9CWX8Y5YVO5iUTD9h3gexnZw9Zuyd6yAAeay+oNmxWMlDhD0FJWKgwo5UQNjO6YmMo0E0wN//2DjS/OjqhkTrz1g+ozA==
    {{- else }}
    PASSWORD: AgCSONjw0/XY5OZQQ4Awg4JAP8qkLbaXGzg49mfjK/AzqjutjLDF3tYHZLTQmRtctFURWygq7F4+HzmbLMNfytYs+e9Zq1luC/kQyNDsY2FS+WRQDQyaCT/U/Gitp1rVweTySLf46j8RMJNIwHlC1QySPps+Idjs6W90qBRqP38ph2VAm+coH+Jk1i9VTA+aAMfuhXG5R0+IoIpRGE/T9J+iinY81vxAN+XJ1zZDRyrc0czDZUmM+dqfQmS3ifJk/yPKhthonbEaQZS7C+nV7XMMgW9Jcd+HL6WlGWghqU2nfj3HwVlSrkld4F5ODM78vOZZaO23U8ir6pMdjZp9mkF69N2r/uJAazc7F1uHXVh9wvZGiIDMJuf2SiAEZk23PnhjhELfB0IjonVzzSkLxpdoaXQhy2WwGzqoqpzs/s0lOb3MKs8K3jtOPGGefLlGtpTygFYl3liy5q742hT19tR0Behdw2m0QSrocTJ/yXmFXUcm3HfyJycM/Xantvjm0Mf7QMFp3GoVPqS5BKJigQeAdT4QwUGKwjq7HUozqEjBJXQK1kE4w88b1153VImnvGwqyDOWDuFeP6nXB2oK236CCkgFjS+qqCHUqH4LkHbS6D5W7Gqw9kuRRSLv8HTjOzmrIWtpjPEMJIQTkRWaTNc2Ye3rOZn2sBI6t8+PtwnCpXv5gAPu6w6AyBDRMHLoMX7YBT6n6cqEL09lpWD5F2y9ZlDuHA==
    {{- end }}
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: olly-secret
      namespace: '{{ .Values.namespace }}'
