apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - name: backend-cm
    behavior: merge
    literals:
      <literals-list>

resources:
  - destination-rule.yaml
  - destination-metrics-rule.yaml

patches:
  - path: service-app-patch.yaml
  - path: deployment-patch.yaml
  - path: virtualservice-patch.yaml
  - path: metrics-virtualservice-patch.yaml
