apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: backend-cm
      data:
        SERVICE_NAME: hint-service
        POSTGRES_SCHEMA_NAME: hin_develop
        AUTH_URL: https://employee.login.int.signal-iduna.org/
        OTEL_SERVICE_NAME: hint-service
        AUTH_USERS: S000325,U167653

resources:
  - destination-rule.yaml
  - destination-metrics-rule.yaml
