apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: "dev-"

resources:
  - hint

configMapGenerator:
  - name: backend-cm
    behavior: merge
    literals:
      - DEPLOYMENT_ENV=dev

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment      

