apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: "dev-"

resources:
  - application-service

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment      
  - path: service-patch.yaml
    target: 
      kind: Service
  - path: metrics-patch.yaml
    target: 
      kind: Service