apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: "dev-"

labels:
  - pairs:
      environment: dev

resources:
  - hint-service-ELPA4-123
  - hint-service-ELPA4-237
  - hint-service
